[feat]: Create okr objective component
nestsolutionsllc/nest-hr pull request #115
Opened 2022-08-05 08:58 UTC by Nasaa1234

- [x] Implemented Create Okr objective component.
- [x] Objective Edit, Delete, Add 
- [x] Add sub Objective

2022-08-05 10:10 UTC, M4nduul requested changes
Edit delete hiihed asuudaltai bn

2022-08-05 10:50 UTC, Nasaa1234 commented
> Edit delete hiihed asuudaltai bn

code ni uu?

2022-08-10 02:21 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/Accordion.tsx
> +  const { title, data, setData, ind } = props;
nerlehdee descriptive name ugmuur bn

2022-08-10 02:21 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/Accordion.tsx
> +
descriptive name

2022-08-10 02:22 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/More.tsx
> +    if (title === "Delete Result") {
descriptive name

2022-08-10 02:22 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/Popever.tsx
> +  const { handleClose, setType, setData, data, collection, setOpen, openPop, setCollection, setEdit, ind1 } = props;
descriptive name

2022-08-10 02:23 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/Popever.tsx
> +                Icon={el.Icon}
descriptive name

2022-08-10 02:23 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/Summary.tsx
> +  const { collection, edit, setCollection, setEdit, data, ind, setData } = props;
descriptive name

2022-08-10 02:24 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/Type.tsx
> +export type dataType = {
what DataType? (descriptive name)

2022-08-10 02:24 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/Type.tsx
> +export type ColType = {
descriptive name

2022-08-10 02:26 UTC, sumiyab commented on frontend/src/components/okr/mainsSreen/Accordion.tsx
> +import { FC, SyntheticEvent, useEffect, useState } from "react";
It is too much long lines for one file coding need to seperate two files.

2022-08-10 02:27 UTC, sumiyab commented
svvld shinechlegdseneer ni pr description oo oorchloorei

2022-08-10 07:29 UTC, M4nduul approved these changes

2022-08-10 07:29 UTC, merged